apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabeh
  namespace: sabeh-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sabeh-app
  template:
    metadata:
      labels:
        app: sabeh-app
    spec:
      automountServiceAccountToken: false

      containers:
        - name: sabeh-app
<<<<<<< Updated upstream
          image: ahmedsabeh/sabeh-app:1.1
=======
          image: ahmedsabeh/sabeh-app:latest  # your Docker Hub image
>>>>>>> Stashed changes
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
