apiVersion: v1
kind: Service
metadata:
  name: sabeh-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ACM_CERT_ARN>"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: sabeh-app
  ports:
    - port: 443
      targetPort: 80

